# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'yajl-ruby', platform: :ruby
gem 'jrjackson', platform: :jruby

# WEBSERVERS
gem 'puma', require: false

platforms :ruby do
  gem 'unicorn', require: false
end